
export const RATINGS = {
  GOOD: 'GOOD',
  NEEDS_IMPROVEMENT: 'NEEDS_IMPROVEMENT',
  POOR: 'POOR',
} as const;

export type Rating = (typeof RATINGS)[keyof typeof RATINGS];

export const WEB_VITALS = {
  CUMULATIVE_LAYOUT_SHIFT: 'CUMULATIVE_LAYOUT_SHIFT',
  FIRST_CONTENTFUL_PAINT: 'FIRST_CONTENTFUL_PAINT',
  FIRST_INPUT_DELAY: 'FIRST_INPUT_DELAY',
  INTERACTION_TO_NEXT_PAINT: 'INTERACTION_TO_NEXT_PAINT',
  LARGEST_CONTENTFUL_PAINT: 'LARGEST_CONTENTFUL_PAINT',
} as const;

export type WebVitalName = (typeof WEB_VITALS)[keyof typeof WEB_VITALS];
